### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by LemonQC** [Ego-J/I2VSGG#1]
您好，请问您图2(a)中的RPN表示什么，还是GRL表示什么，采用什么实现的呢

**Comment by Ego-J** [comment]
RPN是指Region Proposal Network，GRL是Domain-Adversarial Neural Network中的梯度反转层Gradient Reversal Layer

**Comment by Ego-J** [comment]
> 您好，请问您图2(a)中的RPN表示什么，还是GRL表示什么，采用什么实现的呢

RPN是指Region Proposal Network，GRL是Domain-Adversarial Neural Network中的梯度反转层Gradient Reversal Layer
